// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uniflow.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_uniflow_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_uniflow_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_uniflow_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_uniflow_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_uniflow_2eproto;
namespace uniflow {
class UniflowPacket;
struct UniflowPacketDefaultTypeInternal;
extern UniflowPacketDefaultTypeInternal _UniflowPacket_default_instance_;
}  // namespace uniflow
PROTOBUF_NAMESPACE_OPEN
template<> ::uniflow::UniflowPacket* Arena::CreateMaybeMessage<::uniflow::UniflowPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace uniflow {

enum UniflowPacket_PacketType : int {
  UniflowPacket_PacketType_DATA = 0,
  UniflowPacket_PacketType_PARITY = 1,
  UniflowPacket_PacketType_UniflowPacket_PacketType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  UniflowPacket_PacketType_UniflowPacket_PacketType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool UniflowPacket_PacketType_IsValid(int value);
constexpr UniflowPacket_PacketType UniflowPacket_PacketType_PacketType_MIN = UniflowPacket_PacketType_DATA;
constexpr UniflowPacket_PacketType UniflowPacket_PacketType_PacketType_MAX = UniflowPacket_PacketType_PARITY;
constexpr int UniflowPacket_PacketType_PacketType_ARRAYSIZE = UniflowPacket_PacketType_PacketType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UniflowPacket_PacketType_descriptor();
template<typename T>
inline const std::string& UniflowPacket_PacketType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, UniflowPacket_PacketType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function UniflowPacket_PacketType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    UniflowPacket_PacketType_descriptor(), enum_t_value);
}
inline bool UniflowPacket_PacketType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, UniflowPacket_PacketType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<UniflowPacket_PacketType>(
    UniflowPacket_PacketType_descriptor(), name, value);
}
// ===================================================================

class UniflowPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:uniflow.UniflowPacket) */ {
 public:
  inline UniflowPacket() : UniflowPacket(nullptr) {}
  ~UniflowPacket() override;
  explicit PROTOBUF_CONSTEXPR UniflowPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UniflowPacket(const UniflowPacket& from);
  UniflowPacket(UniflowPacket&& from) noexcept
    : UniflowPacket() {
    *this = ::std::move(from);
  }

  inline UniflowPacket& operator=(const UniflowPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline UniflowPacket& operator=(UniflowPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UniflowPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const UniflowPacket* internal_default_instance() {
    return reinterpret_cast<const UniflowPacket*>(
               &_UniflowPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UniflowPacket& a, UniflowPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(UniflowPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UniflowPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UniflowPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UniflowPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UniflowPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UniflowPacket& from) {
    UniflowPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UniflowPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "uniflow.UniflowPacket";
  }
  protected:
  explicit UniflowPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UniflowPacket_PacketType PacketType;
  static constexpr PacketType DATA =
    UniflowPacket_PacketType_DATA;
  static constexpr PacketType PARITY =
    UniflowPacket_PacketType_PARITY;
  static inline bool PacketType_IsValid(int value) {
    return UniflowPacket_PacketType_IsValid(value);
  }
  static constexpr PacketType PacketType_MIN =
    UniflowPacket_PacketType_PacketType_MIN;
  static constexpr PacketType PacketType_MAX =
    UniflowPacket_PacketType_PacketType_MAX;
  static constexpr int PacketType_ARRAYSIZE =
    UniflowPacket_PacketType_PacketType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  PacketType_descriptor() {
    return UniflowPacket_PacketType_descriptor();
  }
  template<typename T>
  static inline const std::string& PacketType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PacketType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PacketType_Name.");
    return UniflowPacket_PacketType_Name(enum_t_value);
  }
  static inline bool PacketType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      PacketType* value) {
    return UniflowPacket_PacketType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kFileNameFieldNumber = 1,
    kPayloadFieldNumber = 5,
    kFileHashFieldNumber = 8,
    kBlockIdFieldNumber = 2,
    kPacketIndexFieldNumber = 3,
    kTypeFieldNumber = 4,
    kPayloadSizeFieldNumber = 6,
    kTotalBlocksFieldNumber = 7,
    kCrc32FieldNumber = 9,
    kFileSizeFieldNumber = 10,
  };
  // string file_name = 1;
  void clear_file_name();
  const std::string& file_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_name();
  PROTOBUF_NODISCARD std::string* release_file_name();
  void set_allocated_file_name(std::string* file_name);
  private:
  const std::string& _internal_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(const std::string& value);
  std::string* _internal_mutable_file_name();
  public:

  // bytes payload = 5;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // bytes file_hash = 8;
  void clear_file_hash();
  const std::string& file_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_hash();
  PROTOBUF_NODISCARD std::string* release_file_hash();
  void set_allocated_file_hash(std::string* file_hash);
  private:
  const std::string& _internal_file_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_hash(const std::string& value);
  std::string* _internal_mutable_file_hash();
  public:

  // uint32 block_id = 2;
  void clear_block_id();
  uint32_t block_id() const;
  void set_block_id(uint32_t value);
  private:
  uint32_t _internal_block_id() const;
  void _internal_set_block_id(uint32_t value);
  public:

  // uint32 packet_index = 3;
  void clear_packet_index();
  uint32_t packet_index() const;
  void set_packet_index(uint32_t value);
  private:
  uint32_t _internal_packet_index() const;
  void _internal_set_packet_index(uint32_t value);
  public:

  // .uniflow.UniflowPacket.PacketType type = 4;
  void clear_type();
  ::uniflow::UniflowPacket_PacketType type() const;
  void set_type(::uniflow::UniflowPacket_PacketType value);
  private:
  ::uniflow::UniflowPacket_PacketType _internal_type() const;
  void _internal_set_type(::uniflow::UniflowPacket_PacketType value);
  public:

  // uint32 payload_size = 6;
  void clear_payload_size();
  uint32_t payload_size() const;
  void set_payload_size(uint32_t value);
  private:
  uint32_t _internal_payload_size() const;
  void _internal_set_payload_size(uint32_t value);
  public:

  // uint32 total_blocks = 7;
  void clear_total_blocks();
  uint32_t total_blocks() const;
  void set_total_blocks(uint32_t value);
  private:
  uint32_t _internal_total_blocks() const;
  void _internal_set_total_blocks(uint32_t value);
  public:

  // uint32 crc32 = 9;
  void clear_crc32();
  uint32_t crc32() const;
  void set_crc32(uint32_t value);
  private:
  uint32_t _internal_crc32() const;
  void _internal_set_crc32(uint32_t value);
  public:

  // uint64 file_size = 10;
  void clear_file_size();
  uint64_t file_size() const;
  void set_file_size(uint64_t value);
  private:
  uint64_t _internal_file_size() const;
  void _internal_set_file_size(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:uniflow.UniflowPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_hash_;
    uint32_t block_id_;
    uint32_t packet_index_;
    int type_;
    uint32_t payload_size_;
    uint32_t total_blocks_;
    uint32_t crc32_;
    uint64_t file_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_uniflow_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UniflowPacket

// string file_name = 1;
inline void UniflowPacket::clear_file_name() {
  _impl_.file_name_.ClearToEmpty();
}
inline const std::string& UniflowPacket::file_name() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.file_name)
  return _internal_file_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UniflowPacket::set_file_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.file_name)
}
inline std::string* UniflowPacket::mutable_file_name() {
  std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:uniflow.UniflowPacket.file_name)
  return _s;
}
inline const std::string& UniflowPacket::_internal_file_name() const {
  return _impl_.file_name_.Get();
}
inline void UniflowPacket::_internal_set_file_name(const std::string& value) {
  
  _impl_.file_name_.Set(value, GetArenaForAllocation());
}
inline std::string* UniflowPacket::_internal_mutable_file_name() {
  
  return _impl_.file_name_.Mutable(GetArenaForAllocation());
}
inline std::string* UniflowPacket::release_file_name() {
  // @@protoc_insertion_point(field_release:uniflow.UniflowPacket.file_name)
  return _impl_.file_name_.Release();
}
inline void UniflowPacket::set_allocated_file_name(std::string* file_name) {
  if (file_name != nullptr) {
    
  } else {
    
  }
  _impl_.file_name_.SetAllocated(file_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_name_.IsDefault()) {
    _impl_.file_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:uniflow.UniflowPacket.file_name)
}

// uint32 block_id = 2;
inline void UniflowPacket::clear_block_id() {
  _impl_.block_id_ = 0u;
}
inline uint32_t UniflowPacket::_internal_block_id() const {
  return _impl_.block_id_;
}
inline uint32_t UniflowPacket::block_id() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.block_id)
  return _internal_block_id();
}
inline void UniflowPacket::_internal_set_block_id(uint32_t value) {
  
  _impl_.block_id_ = value;
}
inline void UniflowPacket::set_block_id(uint32_t value) {
  _internal_set_block_id(value);
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.block_id)
}

// uint32 packet_index = 3;
inline void UniflowPacket::clear_packet_index() {
  _impl_.packet_index_ = 0u;
}
inline uint32_t UniflowPacket::_internal_packet_index() const {
  return _impl_.packet_index_;
}
inline uint32_t UniflowPacket::packet_index() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.packet_index)
  return _internal_packet_index();
}
inline void UniflowPacket::_internal_set_packet_index(uint32_t value) {
  
  _impl_.packet_index_ = value;
}
inline void UniflowPacket::set_packet_index(uint32_t value) {
  _internal_set_packet_index(value);
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.packet_index)
}

// .uniflow.UniflowPacket.PacketType type = 4;
inline void UniflowPacket::clear_type() {
  _impl_.type_ = 0;
}
inline ::uniflow::UniflowPacket_PacketType UniflowPacket::_internal_type() const {
  return static_cast< ::uniflow::UniflowPacket_PacketType >(_impl_.type_);
}
inline ::uniflow::UniflowPacket_PacketType UniflowPacket::type() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.type)
  return _internal_type();
}
inline void UniflowPacket::_internal_set_type(::uniflow::UniflowPacket_PacketType value) {
  
  _impl_.type_ = value;
}
inline void UniflowPacket::set_type(::uniflow::UniflowPacket_PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.type)
}

// bytes payload = 5;
inline void UniflowPacket::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& UniflowPacket::payload() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UniflowPacket::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.payload)
}
inline std::string* UniflowPacket::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:uniflow.UniflowPacket.payload)
  return _s;
}
inline const std::string& UniflowPacket::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void UniflowPacket::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* UniflowPacket::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* UniflowPacket::release_payload() {
  // @@protoc_insertion_point(field_release:uniflow.UniflowPacket.payload)
  return _impl_.payload_.Release();
}
inline void UniflowPacket::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:uniflow.UniflowPacket.payload)
}

// uint32 payload_size = 6;
inline void UniflowPacket::clear_payload_size() {
  _impl_.payload_size_ = 0u;
}
inline uint32_t UniflowPacket::_internal_payload_size() const {
  return _impl_.payload_size_;
}
inline uint32_t UniflowPacket::payload_size() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.payload_size)
  return _internal_payload_size();
}
inline void UniflowPacket::_internal_set_payload_size(uint32_t value) {
  
  _impl_.payload_size_ = value;
}
inline void UniflowPacket::set_payload_size(uint32_t value) {
  _internal_set_payload_size(value);
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.payload_size)
}

// uint32 total_blocks = 7;
inline void UniflowPacket::clear_total_blocks() {
  _impl_.total_blocks_ = 0u;
}
inline uint32_t UniflowPacket::_internal_total_blocks() const {
  return _impl_.total_blocks_;
}
inline uint32_t UniflowPacket::total_blocks() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.total_blocks)
  return _internal_total_blocks();
}
inline void UniflowPacket::_internal_set_total_blocks(uint32_t value) {
  
  _impl_.total_blocks_ = value;
}
inline void UniflowPacket::set_total_blocks(uint32_t value) {
  _internal_set_total_blocks(value);
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.total_blocks)
}

// bytes file_hash = 8;
inline void UniflowPacket::clear_file_hash() {
  _impl_.file_hash_.ClearToEmpty();
}
inline const std::string& UniflowPacket::file_hash() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.file_hash)
  return _internal_file_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UniflowPacket::set_file_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.file_hash)
}
inline std::string* UniflowPacket::mutable_file_hash() {
  std::string* _s = _internal_mutable_file_hash();
  // @@protoc_insertion_point(field_mutable:uniflow.UniflowPacket.file_hash)
  return _s;
}
inline const std::string& UniflowPacket::_internal_file_hash() const {
  return _impl_.file_hash_.Get();
}
inline void UniflowPacket::_internal_set_file_hash(const std::string& value) {
  
  _impl_.file_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* UniflowPacket::_internal_mutable_file_hash() {
  
  return _impl_.file_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* UniflowPacket::release_file_hash() {
  // @@protoc_insertion_point(field_release:uniflow.UniflowPacket.file_hash)
  return _impl_.file_hash_.Release();
}
inline void UniflowPacket::set_allocated_file_hash(std::string* file_hash) {
  if (file_hash != nullptr) {
    
  } else {
    
  }
  _impl_.file_hash_.SetAllocated(file_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_hash_.IsDefault()) {
    _impl_.file_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:uniflow.UniflowPacket.file_hash)
}

// uint32 crc32 = 9;
inline void UniflowPacket::clear_crc32() {
  _impl_.crc32_ = 0u;
}
inline uint32_t UniflowPacket::_internal_crc32() const {
  return _impl_.crc32_;
}
inline uint32_t UniflowPacket::crc32() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.crc32)
  return _internal_crc32();
}
inline void UniflowPacket::_internal_set_crc32(uint32_t value) {
  
  _impl_.crc32_ = value;
}
inline void UniflowPacket::set_crc32(uint32_t value) {
  _internal_set_crc32(value);
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.crc32)
}

// uint64 file_size = 10;
inline void UniflowPacket::clear_file_size() {
  _impl_.file_size_ = uint64_t{0u};
}
inline uint64_t UniflowPacket::_internal_file_size() const {
  return _impl_.file_size_;
}
inline uint64_t UniflowPacket::file_size() const {
  // @@protoc_insertion_point(field_get:uniflow.UniflowPacket.file_size)
  return _internal_file_size();
}
inline void UniflowPacket::_internal_set_file_size(uint64_t value) {
  
  _impl_.file_size_ = value;
}
inline void UniflowPacket::set_file_size(uint64_t value) {
  _internal_set_file_size(value);
  // @@protoc_insertion_point(field_set:uniflow.UniflowPacket.file_size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace uniflow

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::uniflow::UniflowPacket_PacketType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::uniflow::UniflowPacket_PacketType>() {
  return ::uniflow::UniflowPacket_PacketType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_uniflow_2eproto
