# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uniflow.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\runiflow.proto\x12\x07uniflow\"\xfe\x01\n\rUniflowPacket\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x10\n\x08\x62lock_id\x18\x02 \x01(\r\x12\x14\n\x0cpacket_index\x18\x03 \x01(\r\x12/\n\x04type\x18\x04 \x01(\x0e\x32!.uniflow.UniflowPacket.PacketType\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x14\n\x0cpayload_size\x18\x06 \x01(\r\x12\x14\n\x0ctotal_blocks\x18\x07 \x01(\r\x12\x11\n\tfile_hash\x18\x08 \x01(\x0c\x12\r\n\x05\x63rc32\x18\t \x01(\r\"\"\n\nPacketType\x12\x08\n\x04\x44\x41TA\x10\x00\x12\n\n\x06PARITY\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uniflow_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNIFLOWPACKET._serialized_start=27
  _UNIFLOWPACKET._serialized_end=281
  _UNIFLOWPACKET_PACKETTYPE._serialized_start=247
  _UNIFLOWPACKET_PACKETTYPE._serialized_end=281
# @@protoc_insertion_point(module_scope)
