// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uniflow.proto

#include "uniflow.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace uniflow {
PROTOBUF_CONSTEXPR UniflowPacket::UniflowPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.file_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.payload_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.file_hash_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.block_id_)*/0u
  , /*decltype(_impl_.packet_index_)*/0u
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.payload_size_)*/0u
  , /*decltype(_impl_.total_blocks_)*/0u
  , /*decltype(_impl_.crc32_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UniflowPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UniflowPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UniflowPacketDefaultTypeInternal() {}
  union {
    UniflowPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UniflowPacketDefaultTypeInternal _UniflowPacket_default_instance_;
}  // namespace uniflow
static ::_pb::Metadata file_level_metadata_uniflow_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_uniflow_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_uniflow_2eproto = nullptr;

const uint32_t TableStruct_uniflow_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.file_name_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.block_id_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.packet_index_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.payload_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.payload_size_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.total_blocks_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.file_hash_),
  PROTOBUF_FIELD_OFFSET(::uniflow::UniflowPacket, _impl_.crc32_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::uniflow::UniflowPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::uniflow::_UniflowPacket_default_instance_._instance,
};

const char descriptor_table_protodef_uniflow_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\runiflow.proto\022\007uniflow\"\376\001\n\rUniflowPack"
  "et\022\021\n\tfile_name\030\001 \001(\t\022\020\n\010block_id\030\002 \001(\r\022"
  "\024\n\014packet_index\030\003 \001(\r\022/\n\004type\030\004 \001(\0162!.un"
  "iflow.UniflowPacket.PacketType\022\017\n\007payloa"
  "d\030\005 \001(\014\022\024\n\014payload_size\030\006 \001(\r\022\024\n\014total_b"
  "locks\030\007 \001(\r\022\021\n\tfile_hash\030\010 \001(\014\022\r\n\005crc32\030"
  "\t \001(\r\"\"\n\nPacketType\022\010\n\004DATA\020\000\022\n\n\006PARITY\020"
  "\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_uniflow_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_uniflow_2eproto = {
    false, false, 289, descriptor_table_protodef_uniflow_2eproto,
    "uniflow.proto",
    &descriptor_table_uniflow_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_uniflow_2eproto::offsets,
    file_level_metadata_uniflow_2eproto, file_level_enum_descriptors_uniflow_2eproto,
    file_level_service_descriptors_uniflow_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_uniflow_2eproto_getter() {
  return &descriptor_table_uniflow_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_uniflow_2eproto(&descriptor_table_uniflow_2eproto);
namespace uniflow {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UniflowPacket_PacketType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_uniflow_2eproto);
  return file_level_enum_descriptors_uniflow_2eproto[0];
}
bool UniflowPacket_PacketType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr UniflowPacket_PacketType UniflowPacket::DATA;
constexpr UniflowPacket_PacketType UniflowPacket::PARITY;
constexpr UniflowPacket_PacketType UniflowPacket::PacketType_MIN;
constexpr UniflowPacket_PacketType UniflowPacket::PacketType_MAX;
constexpr int UniflowPacket::PacketType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class UniflowPacket::_Internal {
 public:
};

UniflowPacket::UniflowPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:uniflow.UniflowPacket)
}
UniflowPacket::UniflowPacket(const UniflowPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UniflowPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.file_name_){}
    , decltype(_impl_.payload_){}
    , decltype(_impl_.file_hash_){}
    , decltype(_impl_.block_id_){}
    , decltype(_impl_.packet_index_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.payload_size_){}
    , decltype(_impl_.total_blocks_){}
    , decltype(_impl_.crc32_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_file_name().empty()) {
    _this->_impl_.file_name_.Set(from._internal_file_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_payload().empty()) {
    _this->_impl_.payload_.Set(from._internal_payload(), 
      _this->GetArenaForAllocation());
  }
  _impl_.file_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_file_hash().empty()) {
    _this->_impl_.file_hash_.Set(from._internal_file_hash(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.block_id_, &from._impl_.block_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.crc32_) -
    reinterpret_cast<char*>(&_impl_.block_id_)) + sizeof(_impl_.crc32_));
  // @@protoc_insertion_point(copy_constructor:uniflow.UniflowPacket)
}

inline void UniflowPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.file_name_){}
    , decltype(_impl_.payload_){}
    , decltype(_impl_.file_hash_){}
    , decltype(_impl_.block_id_){0u}
    , decltype(_impl_.packet_index_){0u}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.payload_size_){0u}
    , decltype(_impl_.total_blocks_){0u}
    , decltype(_impl_.crc32_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.file_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UniflowPacket::~UniflowPacket() {
  // @@protoc_insertion_point(destructor:uniflow.UniflowPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UniflowPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.file_name_.Destroy();
  _impl_.payload_.Destroy();
  _impl_.file_hash_.Destroy();
}

void UniflowPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UniflowPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:uniflow.UniflowPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.file_name_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  _impl_.file_hash_.ClearToEmpty();
  ::memset(&_impl_.block_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.crc32_) -
      reinterpret_cast<char*>(&_impl_.block_id_)) + sizeof(_impl_.crc32_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UniflowPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string file_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_file_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "uniflow.UniflowPacket.file_name"));
        } else
          goto handle_unusual;
        continue;
      // uint32 block_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.block_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 packet_index = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.packet_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .uniflow.UniflowPacket.PacketType type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::uniflow::UniflowPacket_PacketType>(val));
        } else
          goto handle_unusual;
        continue;
      // bytes payload = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 payload_size = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.payload_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 total_blocks = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.total_blocks_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes file_hash = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_file_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 crc32 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.crc32_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UniflowPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:uniflow.UniflowPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string file_name = 1;
  if (!this->_internal_file_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_file_name().data(), static_cast<int>(this->_internal_file_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "uniflow.UniflowPacket.file_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_file_name(), target);
  }

  // uint32 block_id = 2;
  if (this->_internal_block_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_block_id(), target);
  }

  // uint32 packet_index = 3;
  if (this->_internal_packet_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_packet_index(), target);
  }

  // .uniflow.UniflowPacket.PacketType type = 4;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_type(), target);
  }

  // bytes payload = 5;
  if (!this->_internal_payload().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_payload(), target);
  }

  // uint32 payload_size = 6;
  if (this->_internal_payload_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_payload_size(), target);
  }

  // uint32 total_blocks = 7;
  if (this->_internal_total_blocks() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_total_blocks(), target);
  }

  // bytes file_hash = 8;
  if (!this->_internal_file_hash().empty()) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_file_hash(), target);
  }

  // uint32 crc32 = 9;
  if (this->_internal_crc32() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_crc32(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:uniflow.UniflowPacket)
  return target;
}

size_t UniflowPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uniflow.UniflowPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string file_name = 1;
  if (!this->_internal_file_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_file_name());
  }

  // bytes payload = 5;
  if (!this->_internal_payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_payload());
  }

  // bytes file_hash = 8;
  if (!this->_internal_file_hash().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_file_hash());
  }

  // uint32 block_id = 2;
  if (this->_internal_block_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_block_id());
  }

  // uint32 packet_index = 3;
  if (this->_internal_packet_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_packet_index());
  }

  // .uniflow.UniflowPacket.PacketType type = 4;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 payload_size = 6;
  if (this->_internal_payload_size() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_payload_size());
  }

  // uint32 total_blocks = 7;
  if (this->_internal_total_blocks() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_total_blocks());
  }

  // uint32 crc32 = 9;
  if (this->_internal_crc32() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_crc32());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UniflowPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UniflowPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UniflowPacket::GetClassData() const { return &_class_data_; }


void UniflowPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UniflowPacket*>(&to_msg);
  auto& from = static_cast<const UniflowPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:uniflow.UniflowPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_file_name().empty()) {
    _this->_internal_set_file_name(from._internal_file_name());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if (!from._internal_file_hash().empty()) {
    _this->_internal_set_file_hash(from._internal_file_hash());
  }
  if (from._internal_block_id() != 0) {
    _this->_internal_set_block_id(from._internal_block_id());
  }
  if (from._internal_packet_index() != 0) {
    _this->_internal_set_packet_index(from._internal_packet_index());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_payload_size() != 0) {
    _this->_internal_set_payload_size(from._internal_payload_size());
  }
  if (from._internal_total_blocks() != 0) {
    _this->_internal_set_total_blocks(from._internal_total_blocks());
  }
  if (from._internal_crc32() != 0) {
    _this->_internal_set_crc32(from._internal_crc32());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UniflowPacket::CopyFrom(const UniflowPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uniflow.UniflowPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UniflowPacket::IsInitialized() const {
  return true;
}

void UniflowPacket::InternalSwap(UniflowPacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.file_name_, lhs_arena,
      &other->_impl_.file_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.payload_, lhs_arena,
      &other->_impl_.payload_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.file_hash_, lhs_arena,
      &other->_impl_.file_hash_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UniflowPacket, _impl_.crc32_)
      + sizeof(UniflowPacket::_impl_.crc32_)
      - PROTOBUF_FIELD_OFFSET(UniflowPacket, _impl_.block_id_)>(
          reinterpret_cast<char*>(&_impl_.block_id_),
          reinterpret_cast<char*>(&other->_impl_.block_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UniflowPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_uniflow_2eproto_getter, &descriptor_table_uniflow_2eproto_once,
      file_level_metadata_uniflow_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace uniflow
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::uniflow::UniflowPacket*
Arena::CreateMaybeMessage< ::uniflow::UniflowPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::uniflow::UniflowPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
